title: OE5XRX Dashboard
description: Projektübersicht des Amateurfunkclubs für Remote Stationen

theme: just-the-docs
color_scheme: oe5xrx
logo: "/assets/oe5xrx-logo.svg"
favicon_ico: "/favicon.ico"

aux_links:
  "Hauptseite":
    - "https://oe5xrx.org"
  "GitHub":
    - "https://github.com/OE5XRX"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
