title: OE5XRX Dashboard
description: Projektübersicht des Amateurfunkclubs für Remote Stationen

theme: just-the-docs
favicon_ico: /favicon.ico
logo: "/assets/Icon.png"

aux_links:
  "Hauptseite":
    - "https://oe5xrx.org"
  "GitHub":
    - "https://github.com/OE5XRX"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
